# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=0)),
                ('block_id', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=4)),
                ('vacancy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_year', models.IntegerField(default=0)),
                ('room_no', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
                ('handicapped', models.BooleanField(default=False)),
                ('graduate', models.BooleanField(default=False)),
            ],
        ),
    ]
