# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20160220_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
