# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20160220_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diff',
            name='id',
        ),
        migrations.AlterField(
            model_name='diff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
