# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_auto_20160221_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='room_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Room'),
        ),
    ]
