# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student2', models.CharField(max_length=50)),
                ('accept', models.BooleanField(default=False)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Student')),
            ],
        ),
    ]
