# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='reason',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
