# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_swap_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.Room'),
        ),
    ]
